[package]
name = "scoped-thread-local"
version = "0.1.0"
description = "Highly flexible Scoped thread local with HKT builtin"
keywords = ["scoped-tls", "scoped-thread-local", "macro", "hkt"]
authors = ["storycraft"]
license = "MIT OR Apache-2.0"
edition = "2021"
repository = "https://github.com/storycraft/scoped-thread-local"

[dependencies]
reborrow = "0.5.5"
scopeguard = "1.2.0"
